name: Virtual PC Online

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Configurando o Acesso Remoto
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        
    - name: Criando o Tunel de Conexao
      run: |
        echo "Aguardando configuracao de rede..."
        
    - name: Manter PC Ligado
      run: |
        $loop = $true
        while ($loop) {
          Start-Sleep -Seconds 60
        }
